# Generated by Django 5.0.6 on 2024-07-30 04:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_otp_master_alter_userdata_create_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='type',
            field=models.CharField(default='User', null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='create_by',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 30, 4, 47, 18, 696415, tzinfo=datetime.timezone.utc)),
        ),
    ]
