# Generated by Django 5.0.6 on 2024-07-31 04:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_userdata_type_alter_userdata_create_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='duration_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField()),
            ],
            options={
                'db_table': 'duration_master',
            },
        ),
        migrations.CreateModel(
            name='plan_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField()),
                ('plan_request', models.IntegerField(null=True)),
                ('after_charge', models.CharField(null=True)),
                ('price', models.IntegerField()),
                ('is_unlimited', models.BooleanField(default=False, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('create_at', models.DateTimeField(default=datetime.datetime(2024, 7, 31, 4, 50, 33, 53519, tzinfo=datetime.timezone.utc))),
            ],
            options={
                'db_table': 'plan_master',
            },
        ),
        migrations.RenameField(
            model_name='userdata',
            old_name='updated_by',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='create_by',
        ),
        migrations.AddField(
            model_name='userdata',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 31, 4, 50, 33, 53519, tzinfo=datetime.timezone.utc)),
        ),
    ]
