# Generated by Django 5.0.6 on 2024-07-31 06:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_duration_master_plan_detail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan_detail',
            name='duration_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='plan_detail',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 31, 6, 36, 30, 693394, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 31, 6, 36, 30, 677771, tzinfo=datetime.timezone.utc)),
        ),
    ]
