# Generated by Django 5.0.6 on 2024-08-01 04:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_plan_detail_duration_id_alter_plan_detail_create_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan_detail',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 1, 4, 35, 28, 817829, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 1, 4, 35, 28, 817829, tzinfo=datetime.timezone.utc)),
        ),
    ]
