# Generated by Django 5.0.6 on 2024-08-01 05:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_plan_detail_create_at_alter_userdata_create_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='buy_plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField()),
                ('plan_request', models.IntegerField(null=True)),
                ('after_charge', models.FloatField(null=True)),
                ('price', models.IntegerField()),
                ('is_unlimited', models.BooleanField(default=False, null=True)),
                ('start_date', models.DateTimeField(default=datetime.datetime(2024, 8, 1, 5, 47, 10, 818549, tzinfo=datetime.timezone.utc))),
                ('end_date', models.DateTimeField(null=True)),
                ('plan_id', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'buyplan_master',
            },
        ),
        migrations.AlterField(
            model_name='plan_detail',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 1, 5, 47, 10, 818549, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 1, 5, 47, 10, 818549, tzinfo=datetime.timezone.utc)),
        ),
    ]
