# Generated by Django 5.0.6 on 2024-08-02 09:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_duration_master_days_alter_buy_plan_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan_detail',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='plan_detail',
            name='is_deleted',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='plan_detail',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='buy_plan',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 2, 9, 21, 36, 370163, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='plan_detail',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 2, 9, 21, 36, 370163, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 2, 9, 21, 36, 370163, tzinfo=datetime.timezone.utc)),
        ),
    ]
