# Generated by Django 5.0.6 on 2024-08-20 09:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_buy_plan_start_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='apicall_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField()),
                ('url', models.CharField()),
                ('code', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('data', models.CharField(null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 8, 20, 9, 22, 49, 159082, tzinfo=datetime.timezone.utc))),
            ],
            options={
                'db_table': 'apicall_data',
            },
        ),
        migrations.AlterField(
            model_name='buy_plan',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 20, 9, 22, 49, 159082, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='plan_detail',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 20, 9, 22, 49, 159082, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='pyment_master',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 20, 9, 22, 49, 159082, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 20, 9, 22, 49, 159082, tzinfo=datetime.timezone.utc)),
        ),
    ]
