# Generated by Django 5.0.6 on 2024-08-21 04:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_apicall_data_alter_buy_plan_start_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apicall_data',
            old_name='data',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='apicall_data',
            old_name='url',
            new_name='endpoint',
        ),
        migrations.AddField(
            model_name='apicall_data',
            name='plan_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='apicall_data',
            name='responce',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='apicall_data',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 21, 4, 8, 37, 734160, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='buy_plan',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 21, 4, 8, 37, 727655, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='plan_detail',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 21, 4, 8, 37, 727655, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='pyment_master',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 21, 4, 8, 37, 727655, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 21, 4, 8, 37, 727655, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterModelTable(
            name='apicall_data',
            table='apicall_master',
        ),
    ]
