# Generated by Django 5.0.6 on 2024-09-16 04:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_apicall_data_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='userintrest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('title', models.CharField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 9, 16, 4, 40, 34, 888159, tzinfo=datetime.timezone.utc))),
            ],
            options={
                'db_table': 'userintrest',
            },
        ),
        migrations.AddField(
            model_name='userdata',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='fathername',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='gender',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='mothername',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='occupation',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='position',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='apicall_data',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 16, 4, 40, 34, 888159, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='buy_plan',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 16, 4, 40, 34, 888159, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='notification_master',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 16, 4, 40, 34, 888159, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='plan_detail',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 16, 4, 40, 34, 888159, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='pyment_master',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 16, 4, 40, 34, 888159, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 16, 4, 40, 34, 888159, tzinfo=datetime.timezone.utc)),
        ),
    ]
