# Generated by Django 5.0.6 on 2024-09-16 06:47

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_userintrest_is_active_alter_apicall_data_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='intrestofuser',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='apicall_data',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 16, 6, 47, 8, 3122, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='buy_plan',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 16, 6, 47, 8, 3122, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='notification_master',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 16, 6, 47, 8, 18745, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='plan_detail',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 16, 6, 47, 8, 3122, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='pyment_master',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 16, 6, 47, 8, 3122, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 16, 6, 47, 8, 3122, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userintrest',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 16, 6, 47, 8, 18745, tzinfo=datetime.timezone.utc)),
        ),
    ]
