# Generated by Django 5.1.6 on 2025-03-05 04:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_alter_apicall_data_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apicall_data',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 5, 4, 16, 2, 881653, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='buy_plan',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 5, 4, 16, 2, 880654, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='notification_master',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 5, 4, 16, 2, 881653, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='plan_detail',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 5, 4, 16, 2, 879654, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='pyment_master',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 5, 4, 16, 2, 880654, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 5, 4, 16, 2, 878655, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userintrest',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 5, 4, 16, 2, 881653, tzinfo=datetime.timezone.utc)),
        ),
    ]
