# Generated by Django 5.0.6 on 2024-08-07 10:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_plan_detail_end_date_plan_detail_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy_plan',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='buy_plan',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 7, 10, 19, 3, 973950, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='plan_detail',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 7, 10, 19, 3, 972951, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 7, 10, 19, 3, 970951, tzinfo=datetime.timezone.utc)),
        ),
    ]
