# Generated by Django 5.0.6 on 2024-08-08 12:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_buy_plan_is_active_alter_buy_plan_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy_plan',
            name='afterno_of_request',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='buy_plan',
            name='continue_after',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='buy_plan',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 8, 12, 26, 18, 662187, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='plan_detail',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 8, 12, 26, 18, 661187, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 8, 12, 26, 18, 661187, tzinfo=datetime.timezone.utc)),
        ),
    ]
