# Generated by Django 5.0.6 on 2024-08-14 07:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_buy_plan_afterno_of_request_buy_plan_continue_after_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='pyment_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField()),
                ('amount', models.IntegerField()),
                ('plan_id', models.IntegerField()),
            ],
            options={
                'db_table': 'pyment_master',
            },
        ),
        migrations.AlterField(
            model_name='buy_plan',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 14, 7, 12, 33, 445639, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='plan_detail',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 14, 7, 12, 33, 444640, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 14, 7, 12, 33, 443640, tzinfo=datetime.timezone.utc)),
        ),
    ]
