# Generated by Django 5.0.6 on 2024-08-21 04:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_apicall_data_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apicall_data',
            old_name='body',
            new_name='requestbody',
        ),
        migrations.RenameField(
            model_name='apicall_data',
            old_name='responce',
            new_name='responce_data',
        ),
        migrations.AlterField(
            model_name='apicall_data',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 21, 4, 27, 41, 209609, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='buy_plan',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 21, 4, 27, 41, 209609, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='plan_detail',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 21, 4, 27, 41, 209609, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='pyment_master',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 21, 4, 27, 41, 209609, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 21, 4, 27, 41, 209609, tzinfo=datetime.timezone.utc)),
        ),
    ]
