# Generated by Django 5.0.6 on 2024-09-12 06:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_apicall_data_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='notification_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_user', models.CharField()),
                ('description', models.CharField()),
                ('is_read', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 9, 12, 6, 47, 3, 32287, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.AlterField(
            model_name='apicall_data',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 12, 6, 47, 3, 32287, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='buy_plan',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 12, 6, 47, 3, 31288, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='plan_detail',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 12, 6, 47, 3, 30274, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='pyment_master',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 12, 6, 47, 3, 32287, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 12, 6, 47, 3, 29275, tzinfo=datetime.timezone.utc)),
        ),
    ]
