# Generated by Django 5.0.6 on 2024-09-16 04:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_userintrest_userdata_dob_userdata_fathername_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='grandfathername',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='apicall_data',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 16, 4, 53, 41, 95576, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='buy_plan',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 16, 4, 53, 41, 95576, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='notification_master',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 16, 4, 53, 41, 95576, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='plan_detail',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 16, 4, 53, 41, 95576, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='pyment_master',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 16, 4, 53, 41, 95576, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 16, 4, 53, 41, 95576, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userintrest',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 16, 4, 53, 41, 95576, tzinfo=datetime.timezone.utc)),
        ),
    ]
